import type { Metadata } from 'next'
import { Anuphan } from 'next/font/google'

import { Toaster } from 'react-hot-toast'

import './globals.css'
import { extractRouterConfig } from 'uploadthing/server'
import { ourFileRouter } from './api/uploadthing/core'
import { NextSSRPlugin } from '@uploadthing/react/next-ssr-plugin'
import { Provider as JotaiProvider } from 'jotai'

const anuphan = Anuphan({ subsets: ['thai'] })

export const metadata: Metadata = {
  title: 'Mookrata',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='th'>
      <head />
      <body className={anuphan.className}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />
        <Toaster position='bottom-center' />
        <JotaiProvider>{children}</JotaiProvider>
      </body>
    </html>
  )
}
