import type { Metadata } from 'next'
import { Anuphan } from 'next/font/google'

import { Toaster } from 'react-hot-toast'

import './globals.css'
import { Provider as JotaiProvider } from 'jotai'
import { EdgeStoreProvider } from '../lib/edgestore'

const anuphan = Anuphan({ subsets: ['thai'] })

export const metadata: Metadata = {
  title: 'Mookrata',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='th'>
      <head />
      <body className={anuphan.className}>
        <Toaster position='bottom-center' />
        <EdgeStoreProvider>
          <JotaiProvider>{children}</JotaiProvider>
        </EdgeStoreProvider>
      </body>
    </html>
  )
}
